{
 "title": "Typha Dashborad (Calico)",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "summaries", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "typha_next_breadcrumb_latency_secs",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "typha_next_breadcrumb_latency_secs",
     "legendFormat": "{{quantile}}"
    }
   ]
  },
  {
   "title": "typha_next_breadcrumb_latency_secs_count",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 5, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "typha_next_breadcrumb_latency_secs_count"
    }
   ]
  },
  {
   "title": "Client snapshot send",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 5, "x": 7, "y": 1 },
   "targets": [
    {
     "expr": "typha_client_snapshot_send_secs",
     "legendFormat": "{{quantile}}"
    }
   ]
  },
  {
   "title": "Client snapshot send count",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 12, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "typha_client_snapshot_send_secs_count"
    }
   ]
  },
  {
   "title": "client_write_latency",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 14, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "typha_client_write_latency_secs_count"
    }
   ]
  },
  {
   "title": "typha_next_breadcrumb_latency_secs_count",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 17, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "typha_next_breadcrumb_latency_secs_sum"
    }
   ]
  },
  {
   "title": "Typha connections summary",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 1 },
   "targets": [
    {
     "expr": "rate(typha_connections_accepted[5m])",
     "legendFormat": "Accepted connections"
    },
    {
     "expr": "rate(typha_connections_dropped[5m])",
     "legendFormat": "Dropped connections"
    },
    { "expr": "typha_connections_active", "legendFormat": "Active connections" }
   ]
  },
  {
   "title": "typha logs dropped",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 5, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "typha_logs_dropped{job=\"typha_metrics\"}"
    }
   ]
  },
  {
   "title": "Client snapshot send sum",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "typha_client_snapshot_send_secs_sum"
    }
   ]
  },
  {
   "title": "typha_client_write_latency_secs_sum",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 15, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "typha_client_write_latency_secs_sum"
    }
   ]
  },
  {
   "title": "Typha log errors",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 17, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "typha_log_errors{job=\"typha_metrics\"}"
    }
   ]
  },
  { "title": "kvs and latency", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Typha kvs msg",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 8 },
   "targets": [
    { "expr": "typha_kvs_per_msg", "legendFormat": "{{quantile}}" }
   ]
  },
  {
   "title": "kvs per msg count",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 5, "y": 8 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "typha_kvs_per_msg_count" }
   ]
  },
  {
   "title": "typha_ping_latency",
   "type": "graph",
   "gridPos": { "h": 6, "w": 11, "x": 7, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "typha_ping_latency",
     "legendFormat": "{{instance}}, quantile={{quantile}}"
    }
   ]
  },
  {
   "title": "typha_updates_total",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 8 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "rate(typha_updates_total[5m])" }
   ]
  },
  {
   "title": "typha_updates_skipped",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 8 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "rate(typha_updates_skipped[5m])"
    }
   ]
  },
  {
   "title": "kvs per msg sum",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 5, "y": 11 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "typha_kvs_per_msg_sum" }
   ]
  },
  {
   "title": "typha_ping_latency_sum",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 11 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "typha_ping_latency_sum" }
   ]
  },
  {
   "title": "typha_ping_latency_count",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 11 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "typha_ping_latency_count" }
   ]
  },
  { "title": "General client info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Client latency",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 15 },
   "targets": [
    { "expr": "typha_client_latency_secs", "legendFormat": "{{quantile}}" }
   ]
  },
  {
   "title": "Client latency sum",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 5, "y": 15 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "typha_client_latency_secs_sum" }
   ]
  },
  {
   "title": "typha_client_write_latency",
   "type": "graph",
   "gridPos": { "h": 6, "w": 17, "x": 7, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "typha_client_write_latency_secs",
     "legendFormat": "{{instance}}, quantile={{quantile}}"
    }
   ]
  },
  {
   "title": "Client latency counts",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 5, "y": 18 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "typha_client_latency_secs_count"
    }
   ]
  },
  { "title": "Breadcrumb", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "Breadcrumb size",
   "type": "graph",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "typha_breadcrumb_size",
     "legendFormat": "{{instance}}, quantile={{quantile}}"
    }
   ]
  },
  {
   "title": "Typha breadcrumb block and non block",
   "type": "graph",
   "gridPos": { "h": 7, "w": 10, "x": 11, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(typha_breadcrumb_block[5m])"
    },
    {
     "expr": "rate(typha_breadcrumb_non_block[5m])"
    }
   ]
  },
  {
   "title": "Breadcrumb sequence number",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 21, "y": 22 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "typha_breadcrumb_seq_number" }
   ]
  },
  {
   "title": "Breadcrumb sum size",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 21, "y": 24 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "typha_breadcrumb_size_sum", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Breadcrumb size count",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 26 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "typha_breadcrumb_size_count" }
   ]
  }
 ]
}